# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package files and install dependencies
COPY package.json ./
COPY tsconfig.json ./

# Install dependencies without running scripts (skip prepare if any)
RUN npm install --ignore-scripts

# Copy rest of the application
COPY . ./

# Build the project
RUN npm run build

# Expose any necessary port if required (optional)

# Start the MCP server
CMD ["node", "build/index.js"]
